import React, { createContext, useContext, useState } from 'react';

const translations = {
  ar: {
    // App.jsx
    "dashboard": "🌍 لوحة التحكم",
    "scalper": "⚡ سكالبير",
    "swing": "🏛️ استثمار",
    "sniper": "🧨 سنايبر",
    "analytics": "📈 الأداء والتحليلات",

    // Header.jsx
    "powered_by": "بمحرك Gemini 2.5 Flash المتطور",
    "bot_active": "النظام: نشط ⚔️",
    "bot_paused": "النظام: متوقف ⏸",
    "shield_active": "درع الحماية: فعال 🛡️",
    "shield_inactive": "درع الحماية: غير فعال",
    "standard": "استاندرد",
    "aggressive": "هجومي",
    "opens_in": "يفتح خلال",
    "open": "مفتوح",
    "standby": "انتظار",
    "live": "مباشر",
    "closed": "مغلق",
    "observation_mode": "👁️ وضع المراقبة",
    "trading_mode": "⚔️ وضع التبادل",
    "mt5_market_stopped": "⛔ سوق MT5 متوقف",
    "mt5_no_quotes": "لا تداول — MT5 غير متصل أو لا يوجد سعر حديث من الوسيط",
    "system_paused_note": "التداول متوقف من زر النظام (إيقاف مؤقت)",
    "panic_close": "🚨 إنهاء فوري",

    // MainDashboard.jsx
    "global_control": "🌍 مركز التحكم العالمي",
    "global_control_desc": "إدارة رأس المال الموحد ومراقبة أداء المحركات.",
    "demo_capital": "رأس المال التجريبي ($)",
    "apply_capital": "اعتماد المبلغ",
    "saving": "جاري الحفظ...",
    "applied": "✅ تم الاعتماد",
    "error": "❌ خطأ",
    "account_balance": "رصيد الحساب",
    "equity": "السيولة الجارية",
    "account_info": "معلومات الحساب",
    "demo_account": "حساب تجريبي",
    "loading": "جاري التحميل...",
    "market_engine_status": "حالة محرك السوق",
    "checking": "جاري الفحص...",
    "equity_health": "صحة السيولة وفجوة التراجع (Drawdown)",
    "max_limit_5": "الحد الأقصى: 5.0%",
    "current_drawdown": "التراجع الحالي:",
    "reset_shield": "⚠️ إعادة ضبط حامي السيولة",
    "system_protected": "🛡️ النظام محمي",
    "audit_journal": "📔 سجل التدقيق والقرارات",
    "live_audit": "تدقيق حي",
    "awaiting_logic": "بانتظار دورات منطق السوق...",
    "market_regime_radar": "📡 رادار النظام السوقي",
    "institutional_dist": "التوزيع المؤسسي",
    "bullish": "صاعد",
    "bearish": "هابط",
    "neutral": "محايد",
    "uptrend": "اتجاه صاعد",
    "downtrend": "اتجاه هابط",
    "ranging": "عرضي",
    "undefined": "غير محدد",
    "institutional_protocol": "البروتوكول المؤسسي",
    "execution_guard": "حارس التنفيذ",
    "active": "نشط",
    "equity_shield": "حامي السيولة",
    "limit_5": "حد 5.0%",
    "strategic_pivot": "المحور الاستراتيجي",
    "h4_aligned": "H4 متوافق",
    "v3_5_institutional": "v4.5 Sovereign Edition",
    "liquidity_health": "مؤشر صحة السيولة",
    "global_pulse": "النبض العالمي",
    "conflict_warning": "تعارض (تحيز/اتجاه)",
    "market_regime_radar": "📡 رادار الماتريكس المؤسسي",
    "scalper_rules_engine": "⚡ محرك قوانين السكالبير",
    "engine_version": "إصدار المحرك v2.0",
    "scalper_desc": "إعدادات مستقلة لمحرك السكالبير عالي التردد.",
    "apply_changes": "اعتماد التغييرات",
    "targets_risks": "💰 الأهداف والمخاطر",
    "target_profit": "هدف الربح ($)",
    "safety_stop": "ستوب الأمان ($)",
    "rsi_sensitivity": "🎚️ حساسية RSI",
    "oversold": "تشبع بيعي (شراء)",
    "overbought": "تشبع شرائي (بيع)",
    "points_dist": "📍 النقاط والمسافات",
    "sl_points": "نقاط وقف الخسارة",
    "tp_points": "نقاط أخذ الربح",
    "link_info": "ℹ️ معلومات الربط",
    "link_info_desc": "هذه الإعدادات يتم استهلاكها مباشرة من قبل محلل الذكاء الاصطناعي (Gemini) لإجراء تعديلات حية واتخاذ قرارات الموافقة.",
    "copy_ai_briefing": "📋 نسخ التقرير الشامل (AI Briefing)",
    "briefing_copied": "✅ تم نسخ التقرير الشامل! يمكنك الآن لصقه لـ Gemini للتحليل.",
    "ai_audit_center": "🕵️ مركز التدقيق والتشخيص الذكي",
    "ai_audit_desc": "لقطة نظام كاملة لمعايرة Gemini المستقلة",
    "refresh_scan": "🔄 تحديث الفحص",
    "diagnostic_in_progress": "جاري التقاط ذاكرة النظام...",
    "confluence": "مصفوفة التوافق",

    // SwingDashboard.jsx
    "global_capital_demo": "رأس المال التجريبي العالمي ($)",
    "swing_macro_engine": "🏛️ محرك الاستثمار الكلي (Swing)",
    "engine_v1_2": "إصدار المحرك v1.2",
    "swing_desc": "إعدادات متداول الاتجاه الاستثماري طويل الأمد.",
    "target_points": "نقاط الهدف",
    "basket_target": "هدف السلة ($)",
    "stop_points": "نقاط الوقف",
    "min_confidence": "أدنى ثقة %",
    "max_concurrent": "أقصى صفقات متزامنة",
    "macro_pulse": "نبض الاستثمار الكلي",
    "investing_consensus": "إجماع Investing.com",
    "strong_buy": "شراء قوي",
    "strong_sell": "بيع قوي",
    "buy": "شراء",
    "sell": "بيع",
    "confidence_level": "مستوى الثقة",
    "activation_threshold": "عتبة التفعيل",
    "bot_active_conf": "البوت يعمل عندما تكون الثقة ≥",
    "consulting_market": "جاري استشارة أساسيات السوق...",
    "swing_ready": "🎯 محرك الاستثمار: جاهز — سيبدأ عند الإشارة القوية",
    "swing_standby": "⏸ محرك الاستثمار: في الانتظار — الثقة تحت العتبة",
    "long_term_portfolio": "💼 المحفظة طويلة الأمد",
    "active_holds": "نشط",
    "swing_isolated_desc": "معزول عن السكالبير. محصن ضد ستوب الأمان. أهداف واسعة للتحركات الكبرى.",
    "scanning_pulse": "جاري مسح النبض للمداخل الكلية...",
    "unrealized_pnl": "أرباح/خسائر الاستثمار غير المحققة",
    "pivot_points_radar": "🎯 رادار نقاط الارتكاز (يومي)",
    "institutional_sentiment_matrix": "🏛️ مصفوفة الشعور المؤسسي (Multi-TF)",
    "timeframe": "الإطار",
    "summary": "الخلاصة",
    "ma": "المتوسطات",
    "oscillators": "المؤشرات",
    "patterns": "النماذج",
    "daily": "يومي",
    "entry_logic": "منطق الدخول",
    "entry_logic_desc1": "يفتح فقط عندما يكون إجماع المؤسسات في Investing.com هو",
    "entry_logic_desc2": "مع ثقة ≥",
    "risk_control": "التحكم في المخاطر",
    "risk_desc1": "يستخدم",
    "risk_desc2": "برأس مال",
    "risk_desc3": "الوقف:",
    "risk_desc4": "نقطة. محصن ضد ستوب أمان السكالبير.",
    "profit_target": "هدف الربح",
    "profit_desc1": "يستهدف",
    "profit_desc2": "نقطة أو",
    "profit_desc3": "ربح سلة إجمالي بقيمة",
    "profit_desc4": ". عند الوصول، يتم إغلاق جميع صفقات الاستثمار لتأمين الربح.",

    // SniperDashboard.jsx
    "sniper_fundamental_news": "سنايبر الأخبار الأساسية",
    "engine_v2_data": "محرك v2.0 مدعوم بالبيانات",
    "sniper_desc": "اعتراض التقلبات المؤسسية. يراقب هذا المحرك إصدارات البيانات الاقتصادية وينفذ صفقات بناءً على المفاجآت الإحصائية (الحقيقي مقابل المتوقع).",
    "engine_armed": "المحرك جاهز",
    "engine_standby": "المحرك في الانتظار",
    "disarm": "إيقاف التفعيل",
    "arm_sniper": "تفعيل السنايبر",
    "economic_radar": "📅 رادار المفكرة الاقتصادية",
    "live_feed": "بث مباشر",
    "last_sync": "آخر مزامنة:",
    "no_events_48h": "لم يتم رصد أحداث عالية التأثير في الـ 48 ساعة القادمة.",
    "impact": "تأثير",
    "high": "عالي",
    "medium": "متوسط",
    "engagement_criteria": "معايير الاشتباك",
    "deviation_threshold": "عتبة الانحراف (المفاجأة)",
    "dev_thresh_desc": "أقل فرق بين الحقيقي والمتوقع للتفعيل.",
    "entry_gap": "فجوة الدخول (نقاط)",
    "entry_gap_desc": "مسافة الأمان في حال فقدان البيانات.",
    "precise_lot": "حجم اللوط الدقيق",
    "precise_lot_desc": "حجم التداول لضربات السنايبر ($50: 0.05).",
    "apply_settings": "اعتماد الإعدادات",
    "sniper_protocol_2": "بروتوكول سنايبر 2.0",
    "sniper_protocol_desc1": "عند صدور الخبر، يقارن المحرك بين الحقيقي والمتوقع. إذا تجاوزت المفاجأة",
    "sniper_protocol_desc2": "، يتم تفعيل دخول اتجاهي دقيق فوراً.",
    // Sniper TV Confluence Revisions
    "tv_sniper_title": "قناص التوافق (TradingView)",
    "tv_sniper_desc": "محرك مؤسسي متقدم يبحث عن التوافق عبر إطارات زمنية متعددة وينفذ أوامر معلقة دقيقة عند مستويات الارتكاز (S1/R1) أثناء الإنهاك (RSI Exhaustion).",
    "min_tf_confluence": "الحد الأدنى للتوافق (الأطر الزمنية)",
    "min_tf_desc": "عدد الإطارات (بين 15M، 1H، اليومي) التي تعطي BUY/SELL قوي",
    "limit_vs_market": "آلية التنفيذ: معلق أم بسعر السوق",
    "limit_orders_precision": "أوامر معلقة (Limit Orders)",
    "market_orders_instant": "سعر السوق الفوري",
    "limit_cushion": "وسادة السعر (تعديل السبريد للطلب المعلق)",

    // IntelligencePanel.jsx
    "core_intelligence": "الذكاء الأساسي",
    "adjustment": "تعديل",
    "update_label": "تحديث:",
    "ai_calibrated_msg": "قام الذكاء الاصطناعي بمعايرته ذاتياً {count} مرة.",
    "loading": "جاري التحميل...",
    "never_happened": "لم يحدث بعد",
    "ai_calibration_live": "معايرة الذكاء الاصطناعي: مباشر",
    "ai_thinking_log": "🧠 سجل تفكير الذكاء الاصطناعي",
    "waiting_first_analysis": "بانتظار التحليل الأول للسوق...",

    // AnalyticsDashboard.jsx
    "analytics_title": "تحليلات الأداء المؤسسي",
    "analytics_desc": "مقاييس الأداء ذات الدرجة المؤسسية. تتبع معدلات الربح (Win Rate)، وعوامل الربح (Profit Factor)، وإجمالي رأس المال المحقق عبر جميع المحركات المستقلة.",
    "day": "يومي",
    "week": "أسبوعي",
    "month": "شهري",
    "all": "كل الوقت",
    "engine_breakdown": "آداء المحركات المفصل",
    "applied": "✓ تم التطبيق",
    "param_rsi_oversold": "تشبع بيعي (RSI)",
    "param_rsi_overbought": "تشبع شرائي (RSI)",
    "param_sl_points": "نقاط وقف الخسارة",
    "param_tp_points": "نقاط أخذ الربح",
    "param_virtual_balance": "رأس المال الافتراضي",
    "param_target_profit_usd": "هدف الربح ($)",
    "param_safety_stop_usd": "ستوب الأمان ($)",

    // EvolutionLab.jsx
    "strategy_evolution_lab": "🧬 معمل تطور الاستراتيجية",
    "system_log": "سجل النظام",
    "evolution_desc": "تتبع النمو المنطقي والتعديلات في معايير البوت الأساسية.",
    "fundamental_ai_context": "ذكاء الأخبار الأساسي",
    "ai_lab_monitors": "يراقب مختبر الذكاء الاصطناعي هذه الإشارات للكشف عن التحولات الهيكلية في السوق.",
    "no_evolution_steps": "لا توجد خطوات تطورية موثقة بعد.",
    "ai_adjustment": "تعديل الذكاء الاصطناعي:",
    "trade_failed": "خطأ الصفقة:",
    "unknown": "Unknown",
    "market_footprint": "بصمة السوق",
    "h1_trend": "اتجاه H1",
    "up": "صاعد",
    "down": "هابط",
    "rsi": "RSI",
    "ema_slope": "ميل EMA",
    "initial_params": "المعايير الأولية",
    "optimized_params": "المعايير المُحسّنة",

    // ExposureTable.jsx
    "current_market_exposure": "التعرض الحالي للسوق",
    "ticket": "التذكرة",
    "instrument": "الأداة",
    "strategy": "الاستراتيجية",
    "timeframe": "الإطار",
    "execution": "التنفيذ",
    "volume": "الحجم",
    "floating_pl": "الربح اللحظي",
    "action": "إجراء",
    "no_holds_void": "لا توجد صفقات حالياً...",
    "swing_hold": "🏛️ استثمار",
    "scalp_hold": "⚡ سكالبير",
    "close": "إغلاق",

    // HistoryPanel.jsx
    "unknown": "غير معروف",
    "closed_trades_history": "📜 سجل الصفقات المغلقة",
    "today": "اليوم",
    "last_week": "الأسبوع الماضي",
    "last_month": "الشهر الماضي",
    "last_year": "السنة الماضية",
    "all_time": "كل الوقت",
    "all_engines": "كل المحركات",
    "manual": "👤 يدوي",
    "copy": "📋 نسخ",
    "time": "الوقت",
    "pair": "الزوج",
    "profit_usd": "الربح (USD)",
    "no_trades_match": "لا توجد صفقات تطابق الفلتر.",
    "realized_profit": "الربح المحقق",
    "total": "الإجمالي",

    // LiquidityPanel.jsx
    "live_balance": "الرصيد اللحظي",
    "floating_equity": "الرصيد العائم (Equity)",
    "simulation_mode": "🧪 وضع المحاكاة",
    "sim_desc1": "البوت يخاطر بـ 1% لكل صفقة. يستهدف ربح $",
    "sim_desc2": ". يغلق عند خسارة -$",
    "sim_desc3": ".",
    "start": "البداية:",
    "target": "المستهدف:",
    "safety": "الأمان:",

    // MarketWatch.jsx
    "live_market_watch": "مراقبة السوق الحية",
    "ask": "طلب:",

    // TerminalConsole.jsx
    "bot_engine_output": "مخرجات محرك البوت",
    "live_stream_active": "بث_مباشر:نشط",
    "initializing_stream": "جاري تهيئة البث...",
    "institutional_exec_monitor": "مراقب التنفيذ المؤسسي",
    "level_info": "معلومة",
    "level_warn": "تحذير",
    "level_error": "خطأ",

    // App.jsx
    "session_active": "الجلسة نشطة",
    "opens_in": "يفتح خلال",
    "standby_label": "وضع الاستعداد",
    "checking": "جاري التحقق...",
    "closed": "مغلق",
    "sovereign_strategic_insight": "🧠 رؤية الذكاء الاصطناعي السيادية",
    "active_tweaks": "تعديلات نشطة",
    "live_logic_trace": "📋 تتبع منطق التنفيذ المباشر",
    "real_time": "وقت حقيقي",
    "confluence_heatmap": "📡 خريطة حرارة التوافق"
  },
  en: {
    // App.jsx
    "dashboard": "🌍 Dashboard",
    "scalper": "⚡ Scalper",
    "swing": "🏛️ Swing",
    "sniper": "🧨 Sniper",
    "analytics": "📈 Analytics",

    // Header.jsx
    "powered_by": "Powered by advanced Gemini 2.5 Flash Engine",
    "bot_active": "SYSTEM: ACTIVE ⚔️",
    "bot_paused": "SYSTEM: PAUSED ⏸",
    "shield_active": "SHIELD: ARMED 🛡️",
    "shield_inactive": "SHIELD: DISARMED",
    "standard": "Standard",
    "aggressive": "Aggressive",
    "opens_in": "Opens In",
    "open": "Open",
    "standby": "Standby",
    "live": "Live",
    "closed": "Closed",
    "observation_mode": "👁️ Observation Mode",
    "trading_mode": "⚔️ Trading Mode",
    "mt5_market_stopped": "⛔ MT5 market stopped",
    "mt5_no_quotes": "No trading — MT5 offline or broker has no fresh quotes",
    "system_paused_note": "Paused from system toggle",
    "panic_close": "🚨 Panic Close",

    // MainDashboard.jsx
    "global_control": "🌍 Global Control Center",
    "global_control_desc": "Unified capital management and engine performance monitoring.",
    "demo_capital": "Demo Capital ($)",
    "apply_capital": "Apply Capital",
    "saving": "Saving...",
    "applied": "✅ Applied",
    "error": "❌ Error",
    "account_balance": "Account Balance",
    "equity": "Equity",
    "account_info": "Account Info",
    "demo_account": "Demo Account",
    "loading": "Loading...",
    "market_engine_status": "Market Engine Status",
    "checking": "Checking...",
    "equity_health": "Equity Health & Drawdown",
    "max_limit_5": "Max Limit: 5.0%",
    "current_drawdown": "Current Drawdown:",
    "reset_shield": "⚠️ Reset Equity Shield",
    "system_protected": "🛡️ System Protected",
    "audit_journal": "📔 Audit & Decision Journal",
    "live_audit": "Live Audit",
    "awaiting_logic": "Awaiting market logic cycles...",
    "institutional_dist": "Institutional Distribution",
    "bullish": "Bullish",
    "bearish": "Bearish",
    "neutral": "Neutral",
    "uptrend": "Uptrend",
    "downtrend": "Downtrend",
    "ranging": "Ranging",
    "undefined": "Undefined",
    "institutional_protocol": "Institutional Protocol",
    "execution_guard": "Execution Guard",
    "active": "Active",
    "equity_shield": "Equity Shield",
    "limit_5": "5.0% Limit",
    "strategic_pivot": "Strategic Pivot",
    "h4_aligned": "H4 Aligned",
    "v3_5_institutional": "v4.5 Sovereign Edition",
    "liquidity_health": "Liquidity Health Index",
    "global_pulse": "Global Pulse",
    "conflict_warning": "Conflict (Bias/Trend)",
    "market_regime_radar": "📡 Institutional Matrix Radar",
    "scalper_rules_engine": "⚡ Scalper Rules Engine",
    "engine_version": "Engine v2.0",
    "scalper_desc": "Independent settings for the high-frequency scalper engine.",
    "apply_changes": "Apply Changes",
    "targets_risks": "💰 Targets & Risks",
    "target_profit": "Target Profit ($)",
    "safety_stop": "Safety Stop ($)",
    "rsi_sensitivity": "🎚️ RSI Sensitivity",
    "oversold": "Oversold (Buy)",
    "overbought": "Overbought (Sell)",
    "points_dist": "📍 Points & Distances",
    "sl_points": "Stop Loss Points",
    "tp_points": "Take Profit Points",
    "link_info": "ℹ️ Link Info",
    "link_info_desc": "These settings are consumed directly by the AI analyst (Gemini) to perform live adjustments and approval decisions.",

    // SwingDashboard.jsx
    "global_capital_demo": "Global Demo Capital ($)",
    "swing_macro_engine": "🏛️ Swing Macro Engine",
    "engine_v1_2": "Engine v1.2",
    "swing_desc": "Settings for the long-term trend investment trader.",
    "target_points": "Target Points",
    "basket_target": "Basket Target ($)",
    "stop_points": "Stop Points",
    "min_confidence": "Min Confidence %",
    "max_concurrent": "Max Concurrent Trades",
    "macro_pulse": "Macro Investment Pulse",
    "investing_consensus": "Investing.com Consensus",
    "strong_buy": "Strong Buy",
    "strong_sell": "Strong Sell",
    "buy": "Buy",
    "sell": "Sell",
    "confidence_level": "Confidence Level",
    "activation_threshold": "Activation Threshold",
    "bot_active_conf": "Bot runs when confidence ≥",
    "consulting_market": "Consulting market fundamentals...",
    "pivot_points_radar": "🎯 Pivot Points Radar (Daily)",
    "institutional_sentiment_matrix": "🏛️ Institutional Sentiment Matrix",
    "timeframe": "Period",
    "summary": "Summary",
    "ma": "MAs",
    "oscillators": "Oscillators",
    "patterns": "Patterns",
    "daily": "Daily",
    "swing_ready": "🎯 Swing Engine: Ready — Will trigger on strong signal",
    "swing_standby": "⏸ Swing Engine: Standby — Confidence below threshold",
    "long_term_portfolio": "💼 Long-term Portfolio",
    "active_holds": "Active",
    "swing_isolated_desc": "Isolated from Scalper. Immune to safety stops. Broad targets for major moves.",
    "scanning_pulse": "Scanning pulse for macro entries...",
    "unrealized_pnl": "Unrealized Swing P&L",
    "entry_logic": "Entry Logic",
    "entry_logic_desc1": "Only opens when Investing.com institutional consensus is",
    "entry_logic_desc2": "with confidence ≥",
    "risk_control": "Risk Control",
    "risk_desc1": "Uses",
    "risk_desc2": "with capital",
    "risk_desc3": "Stop:",
    "risk_desc4": "points. Immune to scalper safety stop.",
    "profit_target": "Profit Target",
    "profit_desc1": "Targets",
    "profit_desc2": "points or",
    "profit_desc3": "total basket profit of",
    "profit_desc4": ". Once reached, all swing trades are closed to secure profit.",

    // SniperDashboard.jsx
    "sniper_fundamental_news": "Fundamental News Sniper",
    "engine_v2_data": "Data-Driven Engine v2.0",
    "sniper_desc": "Institutional volatility interception. This engine monitors economic data releases and executes trades based on statistical surprises (Actual vs Forecast).",
    "engine_armed": "Engine Armed",
    "engine_standby": "Engine Standby",
    "disarm": "Disarm",
    "arm_sniper": "Arm Sniper",
    "economic_radar": "📅 Economic Calendar Radar",
    "live_feed": "Live Feed",
    "last_sync": "Last Sync:",
    "no_events_48h": "No high-impact events detected in the next 48 hours.",
    "impact": "Impact",
    "high": "High",
    "medium": "Medium",
    "engagement_criteria": "Engagement Criteria",
    "deviation_threshold": "Deviation Threshold (Surprise)",
    "dev_thresh_desc": "Minimum difference between Actual and Forecast to trigger.",
    "entry_gap": "Entry Gap (Points)",
    "entry_gap_desc": "Safety distance in case of missing data.",
    "precise_lot": "Precise Lot Size",
    "precise_lot_desc": "Trade size for sniper strikes ($50: 0.05).",
    "apply_settings": "Apply Settings",
    "sniper_protocol_2": "Sniper Protocol 2.0",
    "sniper_protocol_desc1": "Upon news release, the engine compares Actual to Forecast. If the surprise exceeds",
    "sniper_protocol_desc2": ", a precise directional entry is triggered immediately.",
    // Sniper TV Confluence Revisions
    "tv_sniper_title": "TradingView Confluence Sniper",
    "tv_sniper_desc": "Advanced institutional engine that hunts for confluence across multiple TradingView timeframes and executes precise limit orders at daily Pivot levels (S1/R1) during extreme RSI exhaustion.",
    "min_tf_confluence": "Minimum TF Confluence",
    "min_tf_desc": "Number of timeframes (out of 15M, 1H, Daily) that MUST agree on STRONG BUY or STRONG SELL.",
    "limit_vs_market": "Limit vs Market Execution",
    "limit_orders_precision": "Limit Orders (Precision)",
    "market_orders_instant": "Market Orders (Instant)",
    "limit_cushion": "Limit Cushion (Spread buffer)",
    "copy_ai_briefing": "📋 Copy Universal AI Briefing",
    "briefing_copied": "✅ AI Briefing Copied! Paste it to Gemini for analysis.",
    "ai_audit_center": "🕵️ AI Diagnostic & Audit Hub",
    "ai_audit_desc": "Full System Snapshot for Gemini Autonomous Tuning",
    "refresh_scan": "🔄 Refresh Scan",
    "diagnostic_in_progress": "Capturing System Memory...",
    "confluence": "Matrix Confluence",

    // IntelligencePanel.jsx
    "core_intelligence": "Core Intelligence",
    "adjustment": "Adjustment",
    "update_label": "Update:",
    "ai_calibrated_msg": "AI autonomously self-calibrated {count} times.",
    "loading": "Loading...",
    "never_happened": "Never",
    "ai_calibration_live": "AI Calibration: LIVE",
    "ai_thinking_log": "🧠 AI Thinking Log",
    "waiting_first_analysis": "Waiting for first market analysis...",
    "applied": "✓ Applied",
    "param_rsi_oversold": "Oversold (RSI)",
    "param_rsi_overbought": "Overbought (RSI)",
    "param_sl_points": "Stop Loss Points",
    "param_tp_points": "Take Profit Points",
    "param_tp_points": "Take Profit Points",
    "param_virtual_balance": "Virtual Balance",
    "param_target_profit_usd": "Target Profit ($)",
    "param_safety_stop_usd": "Safety Stop ($)",

    // EvolutionLab.jsx
    "strategy_evolution_lab": "🧬 Strategy Evolution Lab",
    "system_log": "System Log",
    "evolution_desc": "Track logical growth and adjustments in core bot parameters.",
    "fundamental_ai_context": "Fundamental AI Context",
    "ai_lab_monitors": "The AI Lab monitors these signals to detect structural market shifts.",
    "no_evolution_steps": "No evolution steps documented yet.",
    "ai_adjustment": "AI Adjustment:",
    "trade_failed": "Trade Error:",
    "unknown": "Unknown",
    "market_footprint": "Market Footprint",
    "h1_trend": "H1 Trend",
    "up": "UP",
    "down": "DOWN",
    "rsi": "RSI",
    "ema_slope": "EMA Slope",
    "market_footprint": "Market Footprint",
    "h1_trend": "H1 Trend",
    "up": "UP",
    "down": "DOWN",
    "rsi": "RSI",
    "ema_slope": "EMA Slope",
    "initial_params": "Initial Parameters",
    "optimized_params": "Optimized Parameters",

    // ExposureTable.jsx
    "current_market_exposure": "Current Market Exposure",
    "ticket": "Ticket",
    "instrument": "Instrument",
    "strategy": "Strategy",
    "timeframe": "Timeframe",
    "execution": "Execution",
    "volume": "Volume",
    "floating_pl": "Floating P/L",
    "action": "Action",
    "no_holds_void": "No trades currently...",
    "swing_hold": "🏛️ Swing",
    "scalp_hold": "⚡ Scalper",
    "close": "Close",

    // HistoryPanel.jsx
    "unknown": "Unknown",
    "closed_trades_history": "📜 Closed Trades History",
    "today": "Today",
    "last_week": "Last Week",
    "last_month": "Last Month",
    "last_year": "Last Year",
    "all_time": "All Time",
    "all_engines": "All Engines",
    "manual": "👤 Manual",
    "copy": "📋 Copy",
    "time": "Time",
    "pair": "Pair",
    "profit_usd": "Profit (USD)",
    "no_trades_match": "No trades match the filter.",
    "realized_profit": "Realized Profit",
    "total": "Total",

    // LiquidityPanel.jsx
    "live_balance": "Live Balance",
    "floating_equity": "Floating Equity",
    "simulation_mode": "🧪 Simulation Mode",
    "sim_desc1": "Bot risks 1% per trade. Targets profit of $",
    "sim_desc2": ". Closes on loss of -$",
    "sim_desc3": ".",
    "sim_desc3": ".",
    "start": "Start:",
    "target": "Target:",
    "safety": "Safety:",

    // MarketWatch.jsx
    "live_market_watch": "Live Market Watch",
    "ask": "Ask:",

    // TerminalConsole.jsx
    "bot_engine_output": "Bot Engine Output",
    "live_stream_active": "stream:active",
    "initializing_stream": "Initializing stream...",
    "initializing_stream": "Initializing stream...",
    "institutional_exec_monitor": "Institutional Execution Monitor",
    "level_info": "INFO",
    "level_warn": "WARN",
    "level_error": "ERROR",

    // App.jsx
    "session_active": "Session Active",
    "opens_in": "Opens In",
    "standby_label": "Standby",
    "checking": "Checking...",
    "closed": "Closed",
    "sovereign_strategic_insight": "🧠 Sovereign Strategic Insight",
    "active_tweaks": "Active Tweaks",
    "live_logic_trace": "📋 Live Execution Logic Trace",
    "real_time": "Real-time",
    "confluence_heatmap": "📡 Confluence Heatmap"
  }
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('ar');

  const toggleLang = () => {
    setLang(prev => (prev === 'ar' ? 'en' : 'ar'));
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
